In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
csv_data=pd.read_csv('data/march-data.csv')
display(csv_data)

,Country,Region,Location,Resource Type,floor,Department,seatName,day,00:00,00:10,...,22:20,22:30,22:40,22:50,23:00,23:10,23:20,23:30,23:40,23:50
0,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_1_02,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
1,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_2_02,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
2,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_2_07,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
3,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_1_01,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
4,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_1_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
5,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_2_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
6,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_3_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
7,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_3_01,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
8,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_4_02,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
9,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_3_06,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
10,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_5_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
11,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_5_01,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
13,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_01,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
14,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_09,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
15,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_06,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
16,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_02,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
17,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_07,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
18,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_8_02,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
19,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_05,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
20,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_10,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
21,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_8_07,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
22,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_03,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
23,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_08,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
24,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_10_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
25,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_8_05,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
26,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_01,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
27,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_06,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
28,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_10_02,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
29,India,NaN,Tower 2,Desk,Level 9,Sky Branch,B5_9_11_04,1-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12690,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_25_01,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12691,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_25_06,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12692,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_26_03,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12693,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_27_04,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12694,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_28_02,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12695,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_28_07,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12696,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_28_12,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12697,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_29_03,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12698,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_29_08,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12699,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_31_01,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12700,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_31_06,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12701,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_32_03,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12702,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_32_08,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12703,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_33_04,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12704,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_34_05,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12705,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_35_03,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12706,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_35_08,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12707,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_35_13,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12708,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_36_04,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12709,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_37_02,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12710,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_37_07,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12711,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_38_04,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12712,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_38_09,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12713,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_38_14,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12714,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_39_05,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12715,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_40_03,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12716,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_41_04,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12717,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_41_09,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12718,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_42_04,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0
12719,India,NaN,Tower 2,Desk,Level 10,Sky Branch,B5_10_42_09,8-03-2018,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
def read_base_csv(link):
    csv_data=pd.read_csv(link)
    csv_data['day']=pd.to_datetime(csv_data['day'],dayfirst=True)
    np.datetime64('2015-07-04 12:00')
    return csv_data

def get_col_list(data):
    col_list=[]
    for col in data.columns[8:]:
        col_list.append(col)
    return col_list

def melt_data(data):
    return data.melt(id_vars=['Country','Location','Resource Type','floor','Department','seatName','day'],
                     value_vars=get_col_list(data),
            var_name='Time', value_name='Space')

def parse_time(row):
    import datetime   
    hour,minute=row['Time'].split(':')
    return row['day']+datetime.timedelta(hours=int(hour), minutes=int(minute))
            
def preprocess_csv(link):
    csv_data=read_base_csv(link)
    csv_data=melt_data(csv_data)
    csv_data['Datetime']=csv_data.apply(parse_time,axis=1)
    csv_data.drop(['day','Time'],inplace=True,axis=1)
    csv_data.sort_values(['Datetime','floor','Department'])
    return csv_data

link_list=['march-data','march-data-1','march-data-2','march-data-3']
for i in range(len(link_list)):
    week=preprocess_csv('data/'+link_list[i]+ '.csv')
    print(i,len(week))
    if i==0:
        processed_data=week.copy()
    else:
        processed_data=pd.concat([processed_data,week])
    print(len(processed_data))

0 1831680
1831680
1 1602720
3434400
2 1602720
5037120
3 2060640
7097760

In [26]:
#Create Checkpoint
import pickle
pickle.dump(processed_data,open('processed_data.p','wb'))

In [30]:
processed_data.dtypes

Country                  object
Location                 object
Resource Type            object
floor                    object
Department               object
seatName                 object
Space                     int64
Datetime         datetime64[ns]
dtype: object

In [3]:
import pickle
processed_data=pickle.load(open('processed_data.p', "rb" ))
display(processed_data)

,Country,Location,Resource Type,floor,Department,seatName,Space,Datetime
0,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_1_02,0,2018-03-01 00:00:00
1,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_2_02,0,2018-03-01 00:00:00
2,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_2_07,0,2018-03-01 00:00:00
3,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_1_01,0,2018-03-01 00:00:00
4,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_1_04,0,2018-03-01 00:00:00
5,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_2_04,0,2018-03-01 00:00:00
6,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_3_04,0,2018-03-01 00:00:00
7,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_3_01,0,2018-03-01 00:00:00
8,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_4_02,0,2018-03-01 00:00:00
9,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_3_06,0,2018-03-01 00:00:00
10,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_5_04,0,2018-03-01 00:00:00
11,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_5_01,0,2018-03-01 00:00:00
12,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_04,0,2018-03-01 00:00:00
13,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_01,0,2018-03-01 00:00:00
14,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_09,0,2018-03-01 00:00:00
15,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_6_06,0,2018-03-01 00:00:00
16,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_02,0,2018-03-01 00:00:00
17,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_07,0,2018-03-01 00:00:00
18,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_8_02,0,2018-03-01 00:00:00
19,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_05,0,2018-03-01 00:00:00
20,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_7_10,0,2018-03-01 00:00:00
21,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_8_07,0,2018-03-01 00:00:00
22,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_03,0,2018-03-01 00:00:00
23,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_08,0,2018-03-01 00:00:00
24,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_10_04,0,2018-03-01 00:00:00
25,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_8_05,0,2018-03-01 00:00:00
26,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_01,0,2018-03-01 00:00:00
27,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_9_06,0,2018-03-01 00:00:00
28,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_10_02,0,2018-03-01 00:00:00
29,India,Tower 2,Desk,Level 9,Sky Branch,B5_9_11_04,0,2018-03-01 00:00:00
...,...,...,...,...,...,...,...,...
2060610,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_37_01,0,2018-03-31 23:50:00
2060611,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_38_02,0,2018-03-31 23:50:00
2060612,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_18_04,0,2018-03-31 23:50:00
2060613,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_34_01,0,2018-03-31 23:50:00
2060614,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_25_07,0,2018-03-31 23:50:00
2060615,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_17_03,0,2018-03-31 23:50:00
2060616,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_11_01,0,2018-03-31 23:50:00
2060617,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_6_04,0,2018-03-31 23:50:00
2060618,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_38_03,0,2018-03-31 23:50:00
2060619,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_1_02,0,2018-03-31 23:50:00
2060620,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_42_03,0,2018-03-31 23:50:00
2060621,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_13_06,0,2018-03-31 23:50:00
2060622,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_5_06,0,2018-03-31 23:50:00
2060623,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_15_07,0,2018-03-31 23:50:00
2060624,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_7_07,0,2018-03-31 23:50:00
2060625,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_41_07,0,2018-03-31 23:50:00
2060626,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_6_05,0,2018-03-31 23:50:00
2060627,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_23_03,0,2018-03-31 23:50:00
2060628,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_3_06,0,2018-03-31 23:50:00
2060629,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_41_09,0,2018-03-31 23:50:00
2060630,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_37_04,0,2018-03-31 23:50:00
2060631,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_6_01,0,2018-03-31 23:50:00
2060632,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_18_03,0,2018-03-31 23:50:00
2060633,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_6_03,0,2018-03-31 23:50:00
2060634,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_5_08,0,2018-03-31 23:50:00
2060635,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_17_05,0,2018-03-31 23:50:00
2060636,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_12_09,0,2018-03-31 23:50:00
2060637,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_37_03,0,2018-03-31 23:50:00
2060638,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_33_03,0,2018-03-31 23:50:00
2060639,India,Tower 2,Desk,Level 10,Sky Branch,B5_10_6_02,0,2018-03-31 23:50:00